# compiler_config.yaml
name: "Compiler config file"
version: 1.0
libs:
  std: "/Users/thiagorodrigues/Desktop/IronLang/lib"

compiler:
  output_hlir: "/Users/thiagorodrigues/Desktop/IronLang/temp/hlir"
  output_llvm: "/Users/thiagorodrigues/Desktop/IronLang/temp/llvm"
#  output_executable: "/Users/thiagorodrigues/Desktop/IronLang/temp/build"